### ISSUE TITLE
Test routine needs to have Action as the first column

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/rockmelonqa-ide#142]
Just like test cases

Also Page and Data columns should be active/inactive just like test cases

**Comment by brogreenmoon** [comment]
As per V's comment page and element editing needs to match the test case editor, i.e. these fields are read-only for helper functions that don't refer to a page element, like "Run Code" in the example below:

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/686edc3c-8672-4e7e-b6cf-74319d1d31a7)

**Comment by brogreenmoon** [comment]
Passed:

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/c7b9dd7c-8575-466b-848d-9451d683c3f6)
