### ISSUE TITLE
Test routine needs to support 1, some or all data sets

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/rockmelonqa-ide#143]
When specifying a test routine in a test case, the user should be able to specify:

- 1 data set:  `TestRoutineA[DataSet1]`
- Multiple data sets: `TestRoutineA[DataSet1,DataSet2, DataSet3]`
- All data sets: `TestRoutineA`

**Comment by quockhanh** [comment]
Discussed with @veebs , new UI (and file content data model) will be impleted in #116

**Comment by brogreenmoon** [comment]
Passed.  We didn't explicitly cover the "one dataset" option, but as that's covered by the "some datasets" scenario I think it's fine.

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/6671c43f-01f7-4716-8c0d-202fa276a5b6)

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/0ee0b800-0609-4bed-9835-56e02e546765)

**Comment by brogreenmoon** [comment]
![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/56452fdc-ec63-460c-a2fc-3e75683a5516)
