### ISSUE TITLE
In TestCase, replace testRoutine step by action 'Run Routine'

### ISSUE THREAD

**Issue by quockhanh** [rockmelonqa/rockmelonqa-ide#161]
This is current UI of test case editor, when we add new test routine

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/11658587/33c9d0f4-509a-4cfb-8ff8-f261c9819e1e)

(Red is normal test step, then Blue is routine step)

The problem of this design is, those kind of steps / rows are different together (4 column vs 2 column), and we cannot migrate when implement Grid UI as #118 . I would like to structure them into grid layout right now (same column / row / type)

Solution:   expected UI should look like

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/11658587/47cb6f2c-9a4f-4674-a716-d1a57e6e3633)

- There is new action:   'Run Routine'
- If select, like pagelessa action,  controls under Page and Element columns are disappear
- For the Data column, that is a control likes read-only-textbox, which has the button at the right hand side (Orange square in the mockup).  Click on this button will show a modal / dialog to pick  Routine and **multiple** dataset  (Note: #143 requires to support multiple dataset for routine picker)
- Then, display the selection (readonly text) as  

RoutineName[DataSet1Name, DataSet2Name]   // if enough space
RoutineName[DataSet1Name, DataSet2Name ....   // if not enough space,  when user hover this area, then display full text in a tooltip

About data model, it should be:

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/11658587/c48bc4bb-d445-4c83-8cb8-3cf09fc48753)

- action:  'runRoutine'  
- data:  should be routine id
**- parameters:  That is list of selected data set id (see Vibul's comment)**

**Comment by quockhanh** [comment]
@veebs @vothaison 

For the current test-case-file content model, there is `parameters?: string[]` 
Should we use it instead of create new `dataset` property?  (to contain list of dataset id)

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/11658587/455ee6f4-7cc1-4d82-9b10-c36a069032fb)

**Comment by veebs** [comment]
Yes - let's use the parameters property.

We also should delete the `Add Routine` button.  Don't need it if routine is just another action.

**Comment by brogreenmoon** [comment]
Also refer to the data scenario sections in #118 - they really discuss the data scenario functionality that this ticket and #143 will deliver.

**Comment by quockhanh** [comment]
@brogreenmoon 

This work item is about to redesign (UI) for multiple dataset selection in test case editor. We just change code at TestCaseEditor area

Any change related to 'Run test' dialog should be in separated /other ticket, to figure out the possibility or technical design before any implementation

**Comment by brogreenmoon** [comment]
Implemented:

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/42da5380-07b0-4ef1-b9c6-3496dad2ae06)

and validated Run Test Routine functionality.
