### ISSUE TITLE
Typescript:  Headless mode (run test) does not work

### ISSUE THREAD

**Issue by quockhanh** [rockmelonqa/rockmelonqa-ide#180]
Step to reproduce:

1. Create new project with Typescript
2. Add one or few test cases
3. Gen code
4. Run test with Headless mode

Expectation:   App runs test without browser appearance
Actual:  App runs test with all available browsers (my local is:  Chromium, Firefox, and Webkit) -- see image

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/11658587/928b72bd-44e4-4a37-bfb4-ba57980fd9f3)

TODO:
**Step 1**: 
- Research whether  playwright-typescript support Headless mode or not
- If yes, we should keep this Headless option and fix it (as .NET project). Otherwise, remove this option

**Step 2**:
- For playwright/typescript project, should we add new option like `All browsers`?
- If select, then run with all available browsers on that machine/environment. Then make it as default option
- IMPORTANT: This step neeed @veebs  and @brogreenmoon  's confirmation

**Comment by brogreenmoon** [comment]
Confirmed successful execution as typescript - headless.

I don't think we need an "All browsers" option yet.  Maybe later.
