### ISSUE TITLE
Typescritpt:  Test routine does not work

### ISSUE THREAD

**Issue by quockhanh** [rockmelonqa/rockmelonqa-ide#181]
Step to reproduce:

1. Create new project with Typescript
2. Create 2 test suites.  `Suite-1` just contains list of normal test cases. `Suite-2` contains test-case which uses test routine (multiple dataset) 
3. Gen code then run test
(Contact Khanh to get sample project)

Expactation:  Both test suites can run and passed
Actual:   `Suite-2` fail with coding error  (see image)

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/11658587/316eb2eb-bd4e-4552-8697-bab7f85bd67a)

Error detail:

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/11658587/8f4280af-600a-4197-9ae2-f84926f52c06)

**Comment by quockhanh** [comment]
[typescript.zip](https://github.com/rockmelonqa/rockmelonqa-ide/files/12010713/typescript.zip)

This is sample project for above bug

**Comment by brogreenmoon** [comment]
Confirmed that test routines function using typescript
