### ISSUE TITLE
Typescript: Improve gen code to install `npx playwright install`

### ISSUE THREAD

**Issue by quockhanh** [rockmelonqa/rockmelonqa-ide#183]
For typescript project, when generate code, we miss following step `npx playwright install` so sometimes generated-code is not ready to run test (see image)

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/11658587/951cbef9-2807-47f8-8aef-be6abff07a86)

TODO:  Fix here https://github.com/rockmelonqa/rockmelonqa-ide/blob/c6cc01700d996e226be41477834b53af1d1097da/electron/worker/actions/buildCode.ts#L43

**Comment by brogreenmoon** [comment]
I haven't been able to reproduce this, so I think it's been fixed
