### ISSUE TITLE
Can't find TestRoutine in TestCase

### ISSUE THREAD

**Issue by hanglequan1991** [rockmelonqa/rockmelonqa-ide#198]
![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/101234158/dac8d2e0-8958-46c5-b0fe-d316a30a8cbe)

This error appears when TestRoutine can't be recognized in TestCase

TestCase
![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/101234158/f05af7c1-0166-472f-8558-460d941ef891)

TestRoutine (in subfolder)
![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/101234158/320d0fe2-e54c-4432-9d7d-a11496989392)

**Comment by brogreenmoon** [comment]
Can't reproduce anymore.  I tried to change the name of a test routine in Windows Explorer and it was correctly updated in the IDE
