### ISSUE TITLE
The "Test Id Attribute Name" project setting is not being picked up when executing tests as Typescript

### ISSUE THREAD

**Issue by brogreenmoon** [rockmelonqa/rockmelonqa-ide#207]
![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/12d9970f-2ec7-4db6-b4ee-926492020eab)

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/3430a713-86c3-49ee-ad2b-8f7f2472d315)

But when running as typescript the "data-cy" is not applied and the attribute referenced is "data-testid":

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/7a86dbff-a2cb-422e-b6dc-5179e5d7db6f)

**Comment by vothaison** [comment]
PR: https://github.com/rockmelonqa/rockmelonqa-ide/pull/219
