### ISSUE TITLE
Use default playwright instead of playwright + jest

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/rockmelonqa-ide#22]
When user selects Playwright and Typescript, the generated code should be [Playwright default](https://playwright.dev/docs/intro), not the Playwright+Jest

**Comment by quockhanh** [comment]
Move to backlog,  only support new language (playwright + typescript) whenever we fully support dotnet (ms unit | nunit | xUnit)
Support 2 languages simutanously takes lot of time and effort to fix bug, maintain, add new feature and/or refactor
