### ISSUE TITLE
To be able to see the whole locator when the xpath is very long

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/rockmelonqa-ide#26]
Right now the locator field is quite narrow, so whenever you have a long locator it's quite difficult to see and edit.

![image](https://user-images.githubusercontent.com/367073/231955463-c4a569ec-b21d-4f0b-90b7-e727c26b9893.png)

When the locator text box has focus, show ... at the end of the text box.  If clicked, then popup modal dialog with big text area.

**Comment by quockhanh** [comment]
Should not do it now, we may need to rework when implement [118](https://github.com/rockmelonqa/ide/issues/118)****

**Comment by vothaison** [comment]
Let me start with this one, @veebs 
See how the new grid design holds up.
