### ISSUE TITLE
Minor code formatting issue with the "Close Popup" action

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/rockmelonqa-ide#29]
![image](https://user-images.githubusercontent.com/367073/231958234-38ded4d2-fb03-4b50-9985-9e1268a6914a.png)

**Comment by brogreenmoon** [comment]
It's still not quite right - now it's like this:

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/7eafc30c-f59d-430e-9793-ed20bb8baf70)
