### ISSUE TITLE
Default the page to the page in the previous test step when adding a new test step

### ISSUE THREAD

**Issue by veebs** [rockmelonqa/rockmelonqa-ide#30]
Default the page to the page in the previous test step when adding a new test step.  I think this will make test step creation more user-friendly, especially where there are a lot of pages present and it's tiresome to select the correct page each time in the pages dropdown:

![image](https://user-images.githubusercontent.com/367073/231957256-acab744a-7b78-4c30-8c1c-dd90c7ae9d76.png)

**Comment by quockhanh** [comment]
This task should be confirmed again before any development, because we already move Action column to left side, and there are few pageless action

**Comment by veebs** [comment]
Should default to the last page used (if any) rather than the page in the previous step.  Default should only happy if page is required for that action.

This should apply to test steps and routines.

eg. if the last page used was from step number 5 of 10 and we are adding step number 11, once we select an action that requires a page, the page cell should be enabled with the page name from step 5 pre-filled.

**Comment by hanglequan1991** [comment]
hi @quockhanh , @veebs ,
please help me review this PR https://github.com/rockmelonqa/rockmelonqa-ide/pull/137
Thanks,

**Comment by brogreenmoon** [comment]
Passed.  Confirmed for test case and test routine:

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/25869ab7-1ce4-4798-9116-a55d1be3c0ae)

![image](https://github.com/rockmelonqa/rockmelonqa-ide/assets/114720205/0b0df952-4918-4681-9146-adb5d09d4a75)
