### ISSUE TITLE
Take a screenshot when a test fails

### ISSUE THREAD

**Issue by brogreenmoon** [rockmelonqa/rockmelonqa-ide#66]
![image](https://user-images.githubusercontent.com/114720205/234725481-a7c527de-4c46-426b-bc8a-7551091aa936.png)

**Comment by veebs** [comment]
Save file to the test results folder.

Need mechanism to catch exceptions and then take screenshot for each test method.

Name for error file should be `{FullClassName}_{MethodName}_error.png`.  

Output file name in the log.

**Comment by brogreenmoon** [comment]
Another very similar feature (that Playwright supports natively) is the ability to record a video as the script plays back.  Can we add this as part of this ticket too please?  With the same style of config in play.

**Comment by quockhanh** [comment]
Personally, I think video (ticket 169) is enough. A single screenshot (this ticket) may be not useful to tell us what happens during test process

**Comment by brogreenmoon** [comment]
Passed.  Video recording is working well.
